### ISSUE TITLE
Focus Tree stays on base game version

### ISSUE THREAD

**Issue by josphh** [YummYume/Russia-2.0#45] opened 2020-10-12 11:37 UTC
I've reinstalled the mod, reinstalled the game, and disabled all mods, but the focus tree stays on the base tree. The modifier to block deleting/editing troops is still there, and Stalin's portrait is still there. But The focus tree and the other modifiers are gone.
![image](https://user-images.githubusercontent.com/28985840/95742244-98497000-0c87-11eb-8df0-41f6617cc36f.png)

![image](https://user-images.githubusercontent.com/28985840/95742279-a5665f00-0c87-11eb-99e8-fec1bc4fe99a.png)

**Comment by YummYume** [comment] 2020-10-12 15:31
This is most likely due to mod conflicts. That's the only explanation as to why the base focus tree is still there.

**Comment by josphh** [comment] 2020-10-12 16:04
I have no other mods enabled apart from Russia Reworked, and I'm using all of the new DLC's.

**Comment by YummYume** [comment] 2020-10-12 18:13
Are you using the GitHub or Steam version? Either way, it might have to do with a corrupted installation. Also, make sure you only have one Russia Reworked mod in your mods, otherwise, the launcher will not recognize it properly.

**Comment by josphh** [comment] 2020-10-12 21:44
I'm using the Steam version right now, and I have no other mods named the same. Even after reinstalling the mid I still have the same problem.

**Comment by YummYume** [comment] 2020-10-13 11:26
If you have verified your game files (in case there might be something wrong with them), you might wanna try to use the GitHub version instead and see if it changes anything.

**Comment by josphh** [comment] 2020-10-31 16:46
Didn't work using the GitHub version either, and i'm still having the same problem. Could it be due to my OS? (Linux, Pop!_OS 20.10)

**Comment by YummYume** [comment] 2020-11-05 09:53
Linux should not affect the way the mod works as far as I know.
Here are steps you can try that seem to work for many people within the modding community :

1) Unsubscribe from the mod and resubscribe to it. You may have to attempt this several times. This will fix the issue for the vast majority of people.

2) Unsubscribe from the mod and uninstall HoI4. Then reinstall HoI4 and resubscribe to the mod. It is very rare for this problem to persist after this point.

3) The nuclear option. Complete step 2 again, but before reinstalling HoI4, go to Documents\Paradox Interactive\Hearts of Iron IV. Delete the mod folder. Reinstall HoI4 and start a game with no mods turned on, this should recreate the mod folder that you previously deleted. Subscribe to the mod.

4) The ultra nuclear option (NOTE: THIS WILL UNINSTALL ALL OF YOUR HOI4 MODS AND YOU WILL HAVE TO RESUBSCRIBE TO THEM AGAIN). In your steam app, click on Steam at the top left of the window and select "Backup and Restore Games". Create a backup for HoI4, then uninstall HoI4. Find the game folder in C:\Program Files (x86)\Steam\SteamApps\common\ and delete the Hearts of Iron IV folder if it's there. Then go to Documents\Paradox Interactive and delete the Hearts of Iron IV folder if it's there. Reinstall the game by again going to "Backup and Restore Games", but select Restore Backup this time. This should ensure that when you reinstall the game, it will be as a blank slate.

**Comment by YummYume** [comment] 2020-11-05 09:54
It still really looks like the mod is corrupted for you though. I don't see why you would only get the pictures working. Are you playing on the latest HOI4 version?

**Comment by josphh** [comment] 2020-11-06 21:30
it seems even doing the ultra nuclear option doesn't seem to work. even after unsubscribing from all the mods, uninstalling HOI4 and removing all traces of HOI4 from my system, I still get the same problem. Also, I'm playing on Collie v1.10.1

**Comment by YummYume** [comment] 2020-11-10 22:28
I really don't understand how you're not able to play it... You seem to be having everything right. Perhaps it is Linux causing problems, but I would most likely blame it on Paradox's launcher... I don't see how to make it work apart from trying again and again.

**Comment by santeri-huotari** [comment] 2021-01-01 02:59
So I had the same problem while also using Linux, so I did some investigating and found out what the problem is. Basically there are some folders in the mod files with incorrect letter casing (for example, National_focus should be national_focus), and this stops that folder from being loaded. I'm guessing on Linux casing of the file paths actually matter while on Windows it doesn't.

**Comment by YummYume** [comment] 2021-01-01 12:49
@santeri-huotari Thanks so much. This apparently fixed the issues as you said. We have renamed all the folders properly.
@josphh Hoping this also works for you! Closing this now.

**Closed by YummYume** 2021-01-01 12:49 UTC
Labels: Bug
